'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FileText, Plus } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { useAsync } from '@/hooks/useAsync';
import { usePagination } from '@/hooks/usePagination';
import { useToast } from '@/hooks/useToast';
import { listReports, createReport } from '@/services/api/reports.api';
import { ApiClientError } from '@/services/api/client';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Modal } from '@/components/ui/Modal';
import { Pagination } from '@/components/ui/Pagination';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { SkeletonCard } from '@/components/ui/Skeleton';
import { formatDate } from '@/lib/utils';

function defaultDateRange() {
  const end = new Date();
  const start = new Date();
  start.setDate(start.getDate() - 30);
  return { start: start.toISOString().slice(0, 10), end: end.toISOString().slice(0, 10) };
}

export default function ReportsPage() {
  const router = useRouter();
  const { hasRole } = useAuth();
  const { toast } = useToast();
  const canGenerate = hasRole('ADMIN', 'ANALYST');

  const { page, setPage } = usePagination(10);
  const reports = useAsync(() => listReports(page, 10), [page]);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [title, setTitle] = useState('');
  const defaults = defaultDateRange();
  const [periodStart, setPeriodStart] = useState(defaults.start);
  const [periodEnd, setPeriodEnd] = useState(defaults.end);
  const [isGenerating, setIsGenerating] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setFormError(null);
    if (!title.trim()) {
      setFormError('Report title is required.');
      return;
    }
    setIsGenerating(true);
    try {
      const report = await createReport({
        title,
        periodStart: new Date(periodStart).toISOString(),
        periodEnd: new Date(periodEnd).toISOString(),
      });
      toast.success('Report generated.');
      setIsModalOpen(false);
      router.push(`/reports/${report.id}`);
    } catch (error) {
      setFormError(error instanceof ApiClientError ? error.message : 'Failed to generate report.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-text-primary">Reports</h1>
          <p className="mt-1 text-sm text-text-secondary">Generate and review AI-powered feedback reports.</p>
        </div>
        {canGenerate && (
          <Button variant="primary" size="sm" onClick={() => setIsModalOpen(true)}>
            <Plus className="h-4 w-4" />
            Generate Report
          </Button>
        )}
      </div>

      {reports.error ? (
        <ErrorState message={reports.error.message} onRetry={reports.refetch} />
      ) : reports.isLoading ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <SkeletonCard key={i} />
          ))}
        </div>
      ) : reports.data && reports.data.data.length > 0 ? (
        <Card>
          <CardContent className="divide-y divide-border p-0">
            {reports.data.data.map((report) => (
              <div key={report.id} className="flex items-center justify-between p-4">
                <div>
                  <p className="text-sm font-medium text-text-primary">{report.title}</p>
                  <p className="mt-0.5 text-xs text-text-muted">
                    {formatDate(report.periodStart)} – {formatDate(report.periodEnd)} · Generated by{' '}
                    {report.generatedByUser.name} on {formatDate(report.createdAt)}
                  </p>
                </div>
                <Link href={`/reports/${report.id}`}>
                  <Button variant="outline" size="sm">
                    View
                  </Button>
                </Link>
              </div>
            ))}
          </CardContent>
          <Pagination pagination={reports.data.pagination} onPageChange={setPage} />
        </Card>
      ) : (
        <EmptyState
          icon={FileText}
          title="No reports yet"
          description="Generate your first AI-powered report to get a stakeholder-ready summary of your feedback."
          action={
            canGenerate && (
              <Button variant="primary" size="sm" onClick={() => setIsModalOpen(true)}>
                <Plus className="h-4 w-4" />
                Generate Report
              </Button>
            )
          }
        />
      )}

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Generate Report">
        <div className="space-y-4">
          <Input label="Report title" placeholder="e.g. September 2026 - Monthly Report" value={title} onChange={(e) => setTitle(e.target.value)} required />
          <div className="grid grid-cols-2 gap-3">
            <Input label="From" type="date" value={periodStart} onChange={(e) => setPeriodStart(e.target.value)} required />
            <Input label="To" type="date" value={periodEnd} onChange={(e) => setPeriodEnd(e.target.value)} required />
          </div>
          {formError && <p className="text-sm text-negative">{formError}</p>}
          <p className="text-xs text-text-muted">
            Generating a report aggregates your feedback for this period and writes an AI narrative — this can take up to 15 seconds.
          </p>
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => setIsModalOpen(false)} disabled={isGenerating}>
              Cancel
            </Button>
            <Button variant="primary" onClick={handleGenerate} loading={isGenerating}>
              Generate Report
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
