'use client';

import { useState } from 'react';
import { useParams } from 'next/navigation';
import { ArrowLeft, Download, CheckCircle2 } from 'lucide-react';
import Link from 'next/link';
import { useAsync } from '@/hooks/useAsync';
import { useToast } from '@/hooks/useToast';
import { getReport, downloadReportPdf } from '@/services/api/reports.api';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { SentimentBadge } from '@/components/ui/SentimentBadge';
import { Skeleton } from '@/components/ui/Skeleton';
import { ErrorState } from '@/components/ui/ErrorState';
import { formatDate, channelLabel } from '@/lib/utils';
import type { Sentiment } from '@/types';

function NarrativeSection({ title, text }: { title: string; text: string }) {
  return (
    <div>
      <h3 className="text-sm font-semibold text-text-primary">{title}</h3>
      <p className="mt-1.5 text-sm leading-relaxed text-text-secondary">{text}</p>
    </div>
  );
}

export default function ReportDetailPage() {
  const params = useParams<{ id: string }>();
  const { toast } = useToast();
  const result = useAsync(() => getReport(params.id), [params.id]);
  const report = result.data;
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownloadPdf = async () => {
    if (!report) return;
    setIsDownloading(true);
    try {
      const blob = await downloadReportPdf(report.id);
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const safeName =
        report.title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-+|-+$/g, '') || 'hermesx-report';
      link.href = url;
      link.download = `${safeName}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
    } catch {
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="mx-auto max-w-3xl space-y-6 p-6">
      <div className="flex items-center justify-between" data-hide-on-print="true">
        <Link href="/reports" className="inline-flex items-center gap-1.5 text-sm text-text-secondary hover:text-text-primary">
          <ArrowLeft className="h-4 w-4" />
          Back to reports
        </Link>
        {report && (
          <Button variant="outline" size="sm" onClick={handleDownloadPdf} loading={isDownloading}>
            <Download className="h-4 w-4" />
            Export PDF
          </Button>
        )}
      </div>

      {result.error ? (
        <ErrorState message={result.error.message} onRetry={result.refetch} />
      ) : result.isLoading || !report ? (
        <div className="space-y-4">
          <Skeleton className="h-10 w-2/3" />
          <Skeleton className="h-64" />
        </div>
      ) : (
        <>
          <div>
            <h1 className="text-2xl font-semibold text-text-primary">{report.title}</h1>
            <p className="mt-1 text-sm text-text-muted">
              {formatDate(report.periodStart)} – {formatDate(report.periodEnd)} · Generated by{' '}
              {report.generatedByUser.name} on {formatDate(report.createdAt)}
            </p>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <Card className="p-4 text-center">
              <p className="text-xl font-semibold text-positive">{report.contentJson.stats.positive}</p>
              <p className="text-xs text-text-muted">Positive</p>
            </Card>
            <Card className="p-4 text-center">
              <p className="text-xl font-semibold text-neutral">{report.contentJson.stats.neutral}</p>
              <p className="text-xs text-text-muted">Neutral</p>
            </Card>
            <Card className="p-4 text-center">
              <p className="text-xl font-semibold text-negative">{report.contentJson.stats.negative}</p>
              <p className="text-xs text-text-muted">Negative</p>
            </Card>
          </div>

          {(report.contentJson.stats.unclassified ?? 0) > 0 && (
            <p className="text-xs text-text-muted">
              {report.contentJson.stats.unclassified} of {report.contentJson.stats.totalFeedback} feedback items from
              this period hadn&apos;t been AI-classified yet when this report was generated, and aren&apos;t
              reflected in the sentiment figures above.
            </p>
          )}

          <Card>
            <CardContent className="space-y-6 p-6">
              <NarrativeSection title="Executive Summary" text={report.contentJson.narrative.executiveSummary} />
              <NarrativeSection title="Feedback Overview" text={report.contentJson.narrative.feedbackOverview} />
              <NarrativeSection title="Sentiment Analysis" text={report.contentJson.narrative.sentimentAnalysis} />
              <NarrativeSection title="Top Themes" text={report.contentJson.narrative.topThemes} />

              {report.contentJson.stats.previousPeriod && (
                <div>
                  <h3 className="text-sm font-semibold text-text-primary">vs. Previous Period</h3>
                  <div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-4">
                    {(
                      [
                        ['Total', report.contentJson.stats.totalFeedback, report.contentJson.stats.previousPeriod.totalFeedback],
                        ['Positive', report.contentJson.stats.positive, report.contentJson.stats.previousPeriod.positive],
                        ['Negative', report.contentJson.stats.negative, report.contentJson.stats.previousPeriod.negative],
                        ['Neutral', report.contentJson.stats.neutral, report.contentJson.stats.previousPeriod.neutral],
                      ] as const
                    ).map(([label, current, previous]) => {
                      const delta = previous > 0 ? Math.round(((current - previous) / previous) * 1000) / 10 : null;
                      return (
                        <div key={label} className="rounded-lg border border-border p-3">
                          <p className="text-xs text-text-muted">{label}</p>
                          <p className="text-lg font-semibold text-text-primary">{current}</p>
                          <p className="text-xs text-text-muted">
                            {delta === null ? 'no prior data' : `${delta > 0 ? '+' : ''}${delta}% vs ${previous}`}
                          </p>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              <NarrativeSection title="Major Changes" text={report.contentJson.narrative.majorChanges} />

              <div>
                <h3 className="text-sm font-semibold text-text-primary">Recommended Actions</h3>
                <ul className="mt-2 space-y-2">
                  {report.contentJson.narrative.recommendedActions.map((action, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-text-secondary">
                      <CheckCircle2 className="mt-0.5 h-4 w-4 flex-shrink-0 text-primary" />
                      {action}
                    </li>
                  ))}
                </ul>
              </div>
            </CardContent>
          </Card>

          {report.contentJson.stats.topThemes.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Top Themes This Period</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {report.contentJson.stats.topThemes.map((t) => (
                  <div key={t.id} className="flex items-center justify-between text-sm">
                    <span className="flex items-center gap-2 text-text-primary">
                      <span className="h-2 w-2 rounded-full" style={{ backgroundColor: t.color }} />
                      {t.name}
                    </span>
                    <span className="text-text-muted">
                      {t.count} ({t.percentage}%)
                    </span>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          {report.contentJson.stats.representativeQuotes.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Customer Quotes</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {report.contentJson.stats.representativeQuotes.map((quote, i) => (
                  <div key={i} className="rounded-lg border border-border p-3">
                    <div className="mb-1.5 flex items-center gap-2">
                      <SentimentBadge sentiment={quote.sentiment as Sentiment} />
                      <Badge tone="default">{channelLabel(quote.channel)}</Badge>
                    </div>
                    <p className="text-sm italic text-text-secondary">&ldquo;{quote.content}&rdquo;</p>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}